"""Software Factory workflows."""

from agentic_rag_template.software_factory.architecture_sheet import (
    ArchitectureSheetGenerationError,
    ArchitectureSheetResult,
    generate_architecture_sheet,
)
from agentic_rag_template.software_factory.job_store import (
    ArchitectureGenerationJobStoreError,
    PostgresArchitectureGenerationJobStore,
)
from agentic_rag_template.software_factory.jobs import (
    ARCHITECTURE_GENERATION_STEPS,
    EVENT_LOG,
    EVENT_STEP_COMPLETED,
    EVENT_STEP_FAILED,
    EVENT_STEP_SKIPPED,
    EVENT_STEP_STARTED,
    JOB_STATUS_CANCELED,
    JOB_STATUS_COMPLETED,
    JOB_STATUS_FAILED,
    JOB_STATUS_QUEUED,
    JOB_STATUS_RUNNING,
    TERMINAL_JOB_STATUSES,
    STEP_STATUS_COMPLETED,
    STEP_STATUS_FAILED,
    STEP_STATUS_PENDING,
    STEP_STATUS_RUNNING,
    STEP_STATUS_SKIPPED,
    ArchitectureGenerationEvent,
    ArchitectureGenerationJob,
    ArchitectureGenerationLogEntry,
    ArchitectureGenerationStep,
    ArchitectureGenerationStepDefinition,
    apply_architecture_generation_event,
)

__all__ = [
    "ARCHITECTURE_GENERATION_STEPS",
    "EVENT_LOG",
    "EVENT_STEP_COMPLETED",
    "EVENT_STEP_FAILED",
    "EVENT_STEP_SKIPPED",
    "EVENT_STEP_STARTED",
    "JOB_STATUS_CANCELED",
    "JOB_STATUS_COMPLETED",
    "JOB_STATUS_FAILED",
    "JOB_STATUS_QUEUED",
    "JOB_STATUS_RUNNING",
    "TERMINAL_JOB_STATUSES",
    "STEP_STATUS_COMPLETED",
    "STEP_STATUS_FAILED",
    "STEP_STATUS_PENDING",
    "STEP_STATUS_RUNNING",
    "STEP_STATUS_SKIPPED",
    "ArchitectureGenerationEvent",
    "ArchitectureGenerationJob",
    "ArchitectureGenerationJobStoreError",
    "ArchitectureGenerationLogEntry",
    "ArchitectureGenerationStep",
    "ArchitectureGenerationStepDefinition",
    "ArchitectureSheetGenerationError",
    "ArchitectureSheetResult",
    "PostgresArchitectureGenerationJobStore",
    "apply_architecture_generation_event",
    "generate_architecture_sheet",
]
